# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageEditor.ui'
#
# Created: Mon Nov 30 15:09:32 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 1000)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Tabelas = QtGui.QToolBox(self.centralwidget)
        self.Tabelas.setGeometry(QtCore.QRect(20, 70, 221, 611))
        self.Tabelas.setObjectName(_fromUtf8("Tabelas"))
        self.modelos = QtGui.QWidget()
        self.modelos.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.modelos.setObjectName(_fromUtf8("modelos"))
        self.line1 = QtGui.QLineEdit(self.modelos)
        self.line1.setGeometry(QtCore.QRect(0, 10, 113, 20))
        self.line1.setObjectName(_fromUtf8("line1"))
        self.line2 = QtGui.QLineEdit(self.modelos)
        self.line2.setGeometry(QtCore.QRect(0, 50, 113, 20))
        self.line2.setObjectName(_fromUtf8("line2"))
        self.label_4 = QtGui.QLabel(self.modelos)
        self.label_4.setGeometry(QtCore.QRect(130, 10, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line3 = QtGui.QLineEdit(self.modelos)
        self.line3.setGeometry(QtCore.QRect(0, 90, 113, 20))
        self.line3.setObjectName(_fromUtf8("line3"))
        self.label_5 = QtGui.QLabel(self.modelos)
        self.label_5.setGeometry(QtCore.QRect(130, 50, 81, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.modelos)
        self.label_6.setGeometry(QtCore.QRect(130, 90, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.insert1 = QtGui.QPushButton(self.modelos)
        self.insert1.setGeometry(QtCore.QRect(70, 160, 83, 24))
        self.insert1.setObjectName(_fromUtf8("insert1"))
        self.Tabelas.addItem(self.modelos, _fromUtf8(""))
        self.sindicatos = QtGui.QWidget()
        self.sindicatos.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.sindicatos.setObjectName(_fromUtf8("sindicatos"))
        self.line5 = QtGui.QLineEdit(self.sindicatos)
        self.line5.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.line5.setObjectName(_fromUtf8("line5"))
        self.label_10 = QtGui.QLabel(self.sindicatos)
        self.label_10.setGeometry(QtCore.QRect(130, 10, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.sindicatos)
        self.label_11.setGeometry(QtCore.QRect(130, 50, 81, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line4 = QtGui.QLineEdit(self.sindicatos)
        self.line4.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.line4.setObjectName(_fromUtf8("line4"))
        self.insert2 = QtGui.QPushButton(self.sindicatos)
        self.insert2.setGeometry(QtCore.QRect(80, 160, 83, 24))
        self.insert2.setObjectName(_fromUtf8("insert2"))
        self.Tabelas.addItem(self.sindicatos, _fromUtf8(""))
        self.testes = QtGui.QWidget()
        self.testes.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.testes.setObjectName(_fromUtf8("testes"))
        self.line6 = QtGui.QLineEdit(self.testes)
        self.line6.setGeometry(QtCore.QRect(0, 20, 113, 20))
        self.line6.setObjectName(_fromUtf8("line6"))
        self.line7 = QtGui.QLineEdit(self.testes)
        self.line7.setGeometry(QtCore.QRect(0, 60, 113, 20))
        self.line7.setObjectName(_fromUtf8("line7"))
        self.label_12 = QtGui.QLabel(self.testes)
        self.label_12.setGeometry(QtCore.QRect(120, 60, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.testes)
        self.label_13.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.insert3 = QtGui.QPushButton(self.testes)
        self.insert3.setGeometry(QtCore.QRect(70, 170, 83, 24))
        self.insert3.setObjectName(_fromUtf8("insert3"))
        self.line8 = QtGui.QLineEdit(self.testes)
        self.line8.setGeometry(QtCore.QRect(0, 100, 113, 20))
        self.line8.setObjectName(_fromUtf8("line8"))
        self.label_14 = QtGui.QLabel(self.testes)
        self.label_14.setGeometry(QtCore.QRect(120, 100, 81, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.Tabelas.addItem(self.testes, _fromUtf8(""))
        self.aviao = QtGui.QWidget()
        self.aviao.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.aviao.setObjectName(_fromUtf8("aviao"))
        self.line9 = QtGui.QLineEdit(self.aviao)
        self.line9.setGeometry(QtCore.QRect(0, 20, 113, 20))
        self.line9.setObjectName(_fromUtf8("line9"))
        self.line10 = QtGui.QLineEdit(self.aviao)
        self.line10.setGeometry(QtCore.QRect(0, 60, 113, 20))
        self.line10.setObjectName(_fromUtf8("line10"))
        self.insert4 = QtGui.QPushButton(self.aviao)
        self.insert4.setGeometry(QtCore.QRect(70, 140, 83, 24))
        self.insert4.setObjectName(_fromUtf8("insert4"))
        self.label_15 = QtGui.QLabel(self.aviao)
        self.label_15.setGeometry(QtCore.QRect(130, 60, 81, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.aviao)
        self.label_16.setGeometry(QtCore.QRect(130, 20, 91, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.Tabelas.addItem(self.aviao, _fromUtf8(""))
        self.funcionarios = QtGui.QWidget()
        self.funcionarios.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.funcionarios.setObjectName(_fromUtf8("funcionarios"))
        self.line11 = QtGui.QLineEdit(self.funcionarios)
        self.line11.setGeometry(QtCore.QRect(0, 10, 113, 20))
        self.line11.setObjectName(_fromUtf8("line11"))
        self.line12 = QtGui.QLineEdit(self.funcionarios)
        self.line12.setGeometry(QtCore.QRect(0, 50, 113, 20))
        self.line12.setObjectName(_fromUtf8("line12"))
        self.label_17 = QtGui.QLabel(self.funcionarios)
        self.label_17.setGeometry(QtCore.QRect(120, 50, 81, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.funcionarios)
        self.label_18.setGeometry(QtCore.QRect(120, 10, 91, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.insert5 = QtGui.QPushButton(self.funcionarios)
        self.insert5.setGeometry(QtCore.QRect(70, 160, 83, 24))
        self.insert5.setObjectName(_fromUtf8("insert5"))
        self.label_23 = QtGui.QLabel(self.funcionarios)
        self.label_23.setGeometry(QtCore.QRect(120, 10, 91, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.line11_2 = QtGui.QLineEdit(self.funcionarios)
        self.line11_2.setGeometry(QtCore.QRect(0, 10, 113, 20))
        self.line11_2.setObjectName(_fromUtf8("line11_2"))
        self.Tabelas.addItem(self.funcionarios, _fromUtf8(""))
        self.tecnicos = QtGui.QWidget()
        self.tecnicos.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.tecnicos.setObjectName(_fromUtf8("tecnicos"))
        self.line14 = QtGui.QLineEdit(self.tecnicos)
        self.line14.setGeometry(QtCore.QRect(0, 50, 113, 20))
        self.line14.setObjectName(_fromUtf8("line14"))
        self.insert6 = QtGui.QPushButton(self.tecnicos)
        self.insert6.setGeometry(QtCore.QRect(70, 170, 83, 24))
        self.insert6.setObjectName(_fromUtf8("insert6"))
        self.label_19 = QtGui.QLabel(self.tecnicos)
        self.label_19.setGeometry(QtCore.QRect(120, 50, 81, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tecnicos)
        self.label_20.setGeometry(QtCore.QRect(120, 10, 91, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.line13 = QtGui.QLineEdit(self.tecnicos)
        self.line13.setGeometry(QtCore.QRect(0, 10, 113, 20))
        self.line13.setObjectName(_fromUtf8("line13"))
        self.line15 = QtGui.QLineEdit(self.tecnicos)
        self.line15.setGeometry(QtCore.QRect(0, 90, 113, 20))
        self.line15.setObjectName(_fromUtf8("line15"))
        self.label_21 = QtGui.QLabel(self.tecnicos)
        self.label_21.setGeometry(QtCore.QRect(120, 130, 81, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.line16 = QtGui.QLineEdit(self.tecnicos)
        self.line16.setGeometry(QtCore.QRect(0, 130, 113, 20))
        self.line16.setObjectName(_fromUtf8("line16"))
        self.label_22 = QtGui.QLabel(self.tecnicos)
        self.label_22.setGeometry(QtCore.QRect(120, 90, 91, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.Tabelas.addItem(self.tecnicos, _fromUtf8(""))
        self.controladores = QtGui.QWidget()
        self.controladores.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.controladores.setObjectName(_fromUtf8("controladores"))
        self.line17 = QtGui.QLineEdit(self.controladores)
        self.line17.setGeometry(QtCore.QRect(0, 20, 113, 20))
        self.line17.setObjectName(_fromUtf8("line17"))
        self.line18 = QtGui.QLineEdit(self.controladores)
        self.line18.setGeometry(QtCore.QRect(0, 60, 113, 20))
        self.line18.setObjectName(_fromUtf8("line18"))
        self.insert7 = QtGui.QPushButton(self.controladores)
        self.insert7.setGeometry(QtCore.QRect(70, 170, 83, 24))
        self.insert7.setObjectName(_fromUtf8("insert7"))
        self.label_24 = QtGui.QLabel(self.controladores)
        self.label_24.setGeometry(QtCore.QRect(120, 60, 81, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.controladores)
        self.label_25.setGeometry(QtCore.QRect(120, 20, 101, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.Tabelas.addItem(self.controladores, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.line19 = QtGui.QLineEdit(self.page_8)
        self.line19.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.line19.setObjectName(_fromUtf8("line19"))
        self.label_26 = QtGui.QLabel(self.page_8)
        self.label_26.setGeometry(QtCore.QRect(130, 20, 91, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.page_8)
        self.label_27.setGeometry(QtCore.QRect(130, 60, 81, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.line20 = QtGui.QLineEdit(self.page_8)
        self.line20.setGeometry(QtCore.QRect(10, 60, 113, 20))
        self.line20.setObjectName(_fromUtf8("line20"))
        self.line21 = QtGui.QLineEdit(self.page_8)
        self.line21.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.line21.setObjectName(_fromUtf8("line21"))
        self.label_28 = QtGui.QLabel(self.page_8)
        self.label_28.setGeometry(QtCore.QRect(130, 100, 91, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.line22 = QtGui.QLineEdit(self.page_8)
        self.line22.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.line22.setObjectName(_fromUtf8("line22"))
        self.label_29 = QtGui.QLabel(self.page_8)
        self.label_29.setGeometry(QtCore.QRect(130, 140, 91, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.line23 = QtGui.QLineEdit(self.page_8)
        self.line23.setGeometry(QtCore.QRect(10, 180, 113, 20))
        self.line23.setObjectName(_fromUtf8("line23"))
        self.label_30 = QtGui.QLabel(self.page_8)
        self.label_30.setGeometry(QtCore.QRect(130, 180, 91, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.line24 = QtGui.QLineEdit(self.page_8)
        self.line24.setGeometry(QtCore.QRect(10, 220, 113, 20))
        self.line24.setObjectName(_fromUtf8("line24"))
        self.label_31 = QtGui.QLabel(self.page_8)
        self.label_31.setGeometry(QtCore.QRect(130, 220, 91, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.insert8 = QtGui.QPushButton(self.page_8)
        self.insert8.setGeometry(QtCore.QRect(70, 270, 83, 24))
        self.insert8.setObjectName(_fromUtf8("insert8"))
        self.Tabelas.addItem(self.page_8, _fromUtf8(""))
        self.afiliacao = QtGui.QWidget()
        self.afiliacao.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.afiliacao.setObjectName(_fromUtf8("afiliacao"))
        self.line25 = QtGui.QLineEdit(self.afiliacao)
        self.line25.setGeometry(QtCore.QRect(0, 20, 113, 20))
        self.line25.setObjectName(_fromUtf8("line25"))
        self.label_32 = QtGui.QLabel(self.afiliacao)
        self.label_32.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.afiliacao)
        self.label_33.setGeometry(QtCore.QRect(120, 60, 91, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.line26 = QtGui.QLineEdit(self.afiliacao)
        self.line26.setGeometry(QtCore.QRect(0, 60, 113, 20))
        self.line26.setObjectName(_fromUtf8("line26"))
        self.line27 = QtGui.QLineEdit(self.afiliacao)
        self.line27.setGeometry(QtCore.QRect(0, 100, 113, 20))
        self.line27.setObjectName(_fromUtf8("line27"))
        self.label_34 = QtGui.QLabel(self.afiliacao)
        self.label_34.setGeometry(QtCore.QRect(120, 100, 91, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.insert9 = QtGui.QPushButton(self.afiliacao)
        self.insert9.setGeometry(QtCore.QRect(70, 210, 83, 24))
        self.insert9.setObjectName(_fromUtf8("insert9"))
        self.Tabelas.addItem(self.afiliacao, _fromUtf8(""))
        self.pericia = QtGui.QWidget()
        self.pericia.setGeometry(QtCore.QRect(0, 0, 221, 301))
        self.pericia.setObjectName(_fromUtf8("pericia"))
        self.line28 = QtGui.QLineEdit(self.pericia)
        self.line28.setGeometry(QtCore.QRect(0, 20, 113, 20))
        self.line28.setObjectName(_fromUtf8("line28"))
        self.label_63 = QtGui.QLabel(self.pericia)
        self.label_63.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.pericia)
        self.label_64.setGeometry(QtCore.QRect(120, 60, 81, 16))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.line29 = QtGui.QLineEdit(self.pericia)
        self.line29.setGeometry(QtCore.QRect(0, 60, 113, 20))
        self.line29.setObjectName(_fromUtf8("line29"))
        self.insert10 = QtGui.QPushButton(self.pericia)
        self.insert10.setGeometry(QtCore.QRect(70, 180, 83, 24))
        self.insert10.setObjectName(_fromUtf8("insert10"))
        self.Tabelas.addItem(self.pericia, _fromUtf8(""))
        self.buttonModelos = QtGui.QPushButton(self.centralwidget)
        self.buttonModelos.setGeometry(QtCore.QRect(330, 90, 171, 31))
        self.buttonModelos.setObjectName(_fromUtf8("buttonModelos"))
        self.buttonSindicatos = QtGui.QPushButton(self.centralwidget)
        self.buttonSindicatos.setGeometry(QtCore.QRect(330, 140, 171, 31))
        self.buttonSindicatos.setObjectName(_fromUtf8("buttonSindicatos"))
        self.buttonTecnicos = QtGui.QPushButton(self.centralwidget)
        self.buttonTecnicos.setGeometry(QtCore.QRect(330, 190, 171, 31))
        self.buttonTecnicos.setObjectName(_fromUtf8("buttonTecnicos"))
        self.buttonTecnicosPericia = QtGui.QPushButton(self.centralwidget)
        self.buttonTecnicosPericia.setGeometry(QtCore.QRect(330, 240, 171, 31))
        self.buttonTecnicosPericia.setObjectName(_fromUtf8("buttonTecnicosPericia"))
        self.buttonAprovados = QtGui.QPushButton(self.centralwidget)
        self.buttonAprovados.setGeometry(QtCore.QRect(330, 290, 171, 31))
        self.buttonAprovados.setObjectName(_fromUtf8("buttonAprovados"))
        self.buttonReprovados = QtGui.QPushButton(self.centralwidget)
        self.buttonReprovados.setGeometry(QtCore.QRect(330, 340, 171, 31))
        self.buttonReprovados.setObjectName(_fromUtf8("buttonReprovados"))
        self.buttonAfiliacoes = QtGui.QPushButton(self.centralwidget)
        self.buttonAfiliacoes.setGeometry(QtCore.QRect(330, 390, 171, 31))
        self.buttonAfiliacoes.setObjectName(_fromUtf8("buttonAfiliacoes"))
        self.buttonAviao = QtGui.QPushButton(self.centralwidget)
        self.buttonAviao.setGeometry(QtCore.QRect(330, 440, 171, 31))
        self.buttonAviao.setObjectName(_fromUtf8("buttonAviao"))
        self.alfabetico = QtGui.QCheckBox(self.centralwidget)
        self.alfabetico.setGeometry(QtCore.QRect(340, 490, 97, 22))
        self.alfabetico.setObjectName(_fromUtf8("alfabetico"))
        self.nota = QtGui.QCheckBox(self.centralwidget)
        self.nota.setGeometry(QtCore.QRect(450, 490, 97, 22))
        self.nota.setObjectName(_fromUtf8("nota"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(660, 90, 111, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.line30 = QtGui.QLineEdit(self.centralwidget)
        self.line30.setGeometry(QtCore.QRect(660, 120, 113, 20))
        self.line30.setObjectName(_fromUtf8("line30"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(670, 170, 111, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.line31 = QtGui.QLineEdit(self.centralwidget)
        self.line31.setGeometry(QtCore.QRect(660, 200, 121, 20))
        self.line31.setObjectName(_fromUtf8("line31"))
        self.remove = QtGui.QPushButton(self.centralwidget)
        self.remove.setGeometry(QtCore.QRect(680, 250, 83, 24))
        self.remove.setObjectName(_fromUtf8("remove"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAbrir = QtGui.QAction(MainWindow)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionSalvar = QtGui.QAction(MainWindow)
        self.actionSalvar.setObjectName(_fromUtf8("actionSalvar"))
        self.actionDeletar = QtGui.QAction(MainWindow)
        self.actionDeletar.setObjectName(_fromUtf8("actionDeletar"))
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionFinalizar_Demarca_o = QtGui.QAction(MainWindow)
        self.actionFinalizar_Demarca_o.setObjectName(_fromUtf8("actionFinalizar_Demarca_o"))
        self.actionDesfazer = QtGui.QAction(MainWindow)
        self.actionDesfazer.setObjectName(_fromUtf8("actionDesfazer"))
        self.actionAmpliar = QtGui.QAction(MainWindow)
        self.actionAmpliar.setObjectName(_fromUtf8("actionAmpliar"))
        self.actionReduzir_uma_vez = QtGui.QAction(MainWindow)
        self.actionReduzir_uma_vez.setObjectName(_fromUtf8("actionReduzir_uma_vez"))
        self.actionTamanho_Original = QtGui.QAction(MainWindow)
        self.actionTamanho_Original.setObjectName(_fromUtf8("actionTamanho_Original"))
        self.menuArquivo.addAction(self.actionSair)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabelas.setCurrentIndex(9)
        QtCore.QObject.connect(self.actionSair, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "INSERIR", None))
        self.label_2.setText(_translate("MainWindow", "CONSULTAR", None))
        self.label_3.setText(_translate("MainWindow", "REMOVER", None))
        self.label_4.setText(_translate("MainWindow", "cod_modelo", None))
        self.label_5.setText(_translate("MainWindow", "peso", None))
        self.label_6.setText(_translate("MainWindow", "capacidade", None))
        self.insert1.setText(_translate("MainWindow", "Inserir", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.modelos), _translate("MainWindow", "Modelos", None))
        self.label_10.setText(_translate("MainWindow", "num_sindicato", None))
        self.label_11.setText(_translate("MainWindow", "nome", None))
        self.insert2.setText(_translate("MainWindow", "Inserir", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.sindicatos), _translate("MainWindow", "Sindicatos", None))
        self.label_12.setText(_translate("MainWindow", "nome", None))
        self.label_13.setText(_translate("MainWindow", "num_anac", None))
        self.insert3.setText(_translate("MainWindow", "Inserir", None))
        self.label_14.setText(_translate("MainWindow", "pont_max", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.testes), _translate("MainWindow", "Testes", None))
        self.insert4.setText(_translate("MainWindow", "Inserir", None))
        self.label_15.setText(_translate("MainWindow", "cod_modelo", None))
        self.label_16.setText(_translate("MainWindow", "registro", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.aviao), _translate("MainWindow", "Avião", None))
        self.label_17.setText(_translate("MainWindow", "nome", None))
        self.label_18.setText(_translate("MainWindow", "num_matricula", None))
        self.insert5.setText(_translate("MainWindow", "Inserir", None))
        self.label_23.setText(_translate("MainWindow", "num_matricula", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.funcionarios), _translate("MainWindow", "Funcioários", None))
        self.insert6.setText(_translate("MainWindow", "Inserir", None))
        self.label_19.setText(_translate("MainWindow", "endereço", None))
        self.label_20.setText(_translate("MainWindow", "num_matricula", None))
        self.label_21.setText(_translate("MainWindow", "salário", None))
        self.label_22.setText(_translate("MainWindow", "telefone", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.tecnicos), _translate("MainWindow", "Técnicos", None))
        self.insert7.setText(_translate("MainWindow", "Inserir", None))
        self.label_24.setText(_translate("MainWindow", "data_exame", None))
        self.label_25.setText(_translate("MainWindow", "num_matricula", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.controladores), _translate("MainWindow", "Controladores", None))
        self.label_26.setText(_translate("MainWindow", "num_anac", None))
        self.label_27.setText(_translate("MainWindow", "cod_modelo", None))
        self.label_28.setText(_translate("MainWindow", "num_matricula", None))
        self.label_29.setText(_translate("MainWindow", "data_teste", None))
        self.label_30.setText(_translate("MainWindow", "horas_gastas", None))
        self.label_31.setText(_translate("MainWindow", "pontuação", None))
        self.insert8.setText(_translate("MainWindow", "Inserir", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.page_8), _translate("MainWindow", "Manuntenção", None))
        self.label_32.setText(_translate("MainWindow", "num_matricula", None))
        self.label_33.setText(_translate("MainWindow", "num_membro", None))
        self.label_34.setText(_translate("MainWindow", "num_sindicato", None))
        self.insert9.setText(_translate("MainWindow", "Inserir", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.afiliacao), _translate("MainWindow", "Afiliação", None))
        self.label_63.setText(_translate("MainWindow", "num_matricula", None))
        self.label_64.setText(_translate("MainWindow", "cod_modelo", None))
        self.insert10.setText(_translate("MainWindow", "Inserir", None))
        self.Tabelas.setItemText(self.Tabelas.indexOf(self.pericia), _translate("MainWindow", "Perícia", None))
        self.buttonModelos.setText(_translate("MainWindow", "Todos os Modelos", None))
        self.buttonSindicatos.setText(_translate("MainWindow", "Todos os Sindicatos", None))
        self.buttonTecnicos.setText(_translate("MainWindow", "Todos os Técnicos", None))
        self.buttonTecnicosPericia.setText(_translate("MainWindow", "Técnicos e Suas Perícias", None))
        self.buttonAprovados.setText(_translate("MainWindow", "Modelos Aprovados", None))
        self.buttonReprovados.setText(_translate("MainWindow", "Modelos Reprovados", None))
        self.buttonAfiliacoes.setText(_translate("MainWindow", "Afiliações", None))
        self.buttonAviao.setText(_translate("MainWindow", "Aviões em Ordem", None))
        self.alfabetico.setText(_translate("MainWindow", "Alfabética", None))
        self.nota.setText(_translate("MainWindow", "Nota", None))
        self.label_35.setText(_translate("MainWindow", "Nome da Tabela:", None))
        self.label_36.setText(_translate("MainWindow", "Campo Chave:", None))
        self.remove.setText(_translate("MainWindow", "Remover", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir...", None))
        self.actionAbrir.setToolTip(_translate("MainWindow", "Abrir Imagem", None))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar...", None))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionDeletar.setText(_translate("MainWindow", "Deletar", None))
        self.actionDeletar.setToolTip(_translate("MainWindow", "Deletar Imagem", None))
        self.actionDeletar.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionSair.setText(_translate("MainWindow", "Sair", None))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionFinalizar_Demarca_o.setText(_translate("MainWindow", "Finalizar Demarcação", None))
        self.actionFinalizar_Demarca_o.setShortcut(_translate("MainWindow", "Ctrl+B", None))
        self.actionDesfazer.setText(_translate("MainWindow", "Desfazer", None))
        self.actionDesfazer.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionAmpliar.setText(_translate("MainWindow", "Ampliar", None))
        self.actionAmpliar.setShortcut(_translate("MainWindow", "Ctrl+=", None))
        self.actionReduzir_uma_vez.setText(_translate("MainWindow", "Reduzir uma vez", None))
        self.actionReduzir_uma_vez.setShortcut(_translate("MainWindow", "Ctrl+-", None))
        self.actionTamanho_Original.setText(_translate("MainWindow", "Tamanho Original", None))
        self.actionTamanho_Original.setShortcut(_translate("MainWindow", "Ctrl+R", None))

