import MySQLdb
con = MySQLdb.connect(host='127.0.0.1', user='root', passwd='221488',db='testepy')
c = con.cursor()

def dell(c):
	c.execute("drop table pericia;")
	c.execute("drop table afiliacao;")
	c.execute("drop table manutencao;")
	c.execute("drop table controladores;")
	c.execute("drop table tecnicos;")
	c.execute("drop table funcionarios;")
	c.execute("drop table aviao;")
	c.execute("drop table testes;")
	c.execute("drop table sindicatos;")
	c.execute("drop table modelos;")
	con.commit()

def algo(c):
	c.execute("create table modelos(cod_modelo int,peso double,capacidade int,PRIMARY KEY (cod_modelo));")
	c.execute("insert into modelos values (1,1000,10);")
	con.commit()
	c.execute("create table sindicatos(num_sindicado int,nome varchar(50),PRIMARY KEY (num_sindicado));")
	c.execute("insert into sindicatos values (10,'Shane');")
	con.commit()
	c.execute("create table testes(num_anac_testes int,nome varchar(50),pont_max int,PRIMARY KEY (num_anac_testes));")
#	c.execute("insert into testes values (1,'Christopher',30);")
	con.commit()
	c.execute("create table aviao (registro int,cod_modelo_aviao int,PRIMARY KEY (registro),FOREIGN KEY (cod_modelo_aviao) REFERENCES modelos(cod_modelo));")
	c.execute("insert into aviao values (15,1);")
	con.commit()
	#ok
	c.execute("create table funcionarios(num_matricula_funcionarios int,nome varchar(50),PRIMARY KEY (num_matricula_funcionarios));")
	c.execute("insert into funcionarios values (3,'Jimmie');")
	con.commit()
	c.execute("create table tecnicos(num_matricula_tecnicos int,endereco varchar(50),telefone varchar(10),salario int,PRIMARY KEY (num_matricula_tecnicos),FOREIGN KEY (num_matricula_tecnicos) REFERENCES funcionarios(num_matricula_funcionarios));")
	c.execute("insert into tecnicos values (3,'Rua Molly',11772294,3500);")
	con.commit()
	c.execute("create table controladores(num_matricula_controladores int,data_exame varchar(8),PRIMARY KEY (num_matricula_controladores),FOREIGN KEY (num_matricula_controladores) REFERENCES funcionarios(num_matricula_funcionarios));")
	c.execute("insert into controladores values (3,'21052015');")
	con.commit()
	c.execute("create table manutencao(num_anac_manutencao int,cod_modelo_manutencao int,num_matricula_manutencao int,data_teste varchar(8),horas_gastas double,pontuacao int, PRIMARY KEY (num_anac_manutencao),FOREIGN KEY (num_anac_manutencao) REFERENCES testes(num_anac_testes),FOREIGN KEY (cod_modelo_manutencao) REFERENCES modelos(cod_modelo),FOREIGN KEY (num_matricula_manutencao) REFERENCES funcionarios(num_matricula_funcionarios));")
#	c.execute("insert into manutencao values (5,5,5,'10082015',2,10);")
	con.commit()
	c.execute("create table afiliacao(num_matricula_afiliacao int,num_membro int,num_sindicato_afiliacao int,PRIMARY KEY (num_matricula_afiliacao),FOREIGN KEY (num_matricula_afiliacao) REFERENCES funcionarios(num_matricula_funcionarios),FOREIGN KEY (num_sindicato_afiliacao) REFERENCES sindicatos(num_sindicado));")
#	c.execute("insert into afiliacao values (8,18,109);")
	con.commit()
	c.execute("create table pericia(num_matricula_pericia int,cod_modelo_pericia int,PRIMARY KEY (num_matricula_pericia,cod_modelo_pericia),FOREIGN KEY (num_matricula_pericia) REFERENCES funcionarios(num_matricula_funcionarios),FOREIGN KEY (cod_modelo_pericia) REFERENCES modelos(cod_modelo));")
#	c.execute("insert into pericia values (4,5);")
	con.commit()

#dell(c)
algo(c)

